version: 2.1

executors:
  exec_make_gcc:
    docker:
      - image: alpine:latest
    working_directory: /app

jobs:
  make_gcc:
    executor: exec_make_gcc   
    steps:
      - setup_remote_docker
      - checkout
      - run:
          command: |
            apk add --update --no-cache build-base 
      - run: make -C src
      - run:
          command: |
            mkdir -p /opt/ms
            cp ./src/microsocks /opt/ms
            cp Dockerfile /opt/ms
            cp init.sh /opt/ms
      - store_artifacts:
          path: /opt/ms
          destination: ms
      - persist_to_workspace:
          root: /opt
          paths:
            - ms

  build_docker_alpine:
    working_directory: ./
    machine: true
    steps:
      - attach_workspace:
          at: ./
      - run:
          command : |
            cp ms/microsocks /home/circleci      
            cp ms/Dockerfile /home/circleci
            cp ms/init.sh ./ 
            cd ./
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin
            docker build -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME .
            docker tag $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:1.0.<< pipeline.number >>-alpine
            docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
  
  build_docker_photon:
    working_directory: main
    machine: true
    steps:
      - checkout
      - run:
          command : |
            cd main
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin
            docker build -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME -f photon/Dockerfile .
            docker tag $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:1.0.<< pipeline.number >>-photon
            docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME          


workflows:
  build-and-publish-docker-image:
    jobs:
      - make_gcc
      - build_docker_alpine:  
          requires:
            - make_gcc
      - build_docker_photon                                     